## Assignment 2

### Zachary Pilbean

### Version 1

### DS 160-01

In [38]:
import numpy as np
array1=np.arange(10,50,10)
array1

array([10, 20, 30, 40])

In [5]:
array1**2

array([ 100,  400,  900, 1600], dtype=int32)

In [6]:
array1+100

array([110, 120, 130, 140])

In [7]:
array1*5

array([ 50, 100, 150, 200])

In [11]:
array1**.5

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [13]:
array2=np.arange(3,28,3)
array2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [15]:
array3=np.linspace(10,20,9)
array3

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [16]:
array2 * array3

array([ 30. ,  67.5, 112.5, 165. , 225. , 292.5, 367.5, 450. , 540. ])

In [17]:
p1=np.load('process1.npy')
p1

array([[52, 12, 81,  0, 58]])

In [18]:
p2=np.load('process2.npy')
p2

array([[96,  4, 61, 16, 43]])

In [19]:
p3=np.load('process3.npy')
p3

array([[38, 96, 45, 17, 58]])

In [20]:
p4=np.load('process4.npy')
p4

array([[97, 21, 22, 25,  6]])

In [21]:
p5=np.load('process5.npy')
p5

array([[77,  6, 19,  2, 74]])

In [25]:
x=np.vstack([p1,p2,p3,p4,p5])
x

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [29]:
np.mean(x[:, :1])

72.0

In [30]:
np.mean(x[:, 1:2])

27.8

In [32]:
np.mean(x[:, 2:3])

45.6

In [33]:
np.mean(x[:, 3:4])

12.0

In [37]:
np.mean(x[:, 4:])

47.8